// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WEB.Data;

#nullable disable

namespace WEB.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251121012556_DataReativar")]
    partial class DataReativar
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WEB.Models.Entities.Diaconato", b =>
                {
                    b.Property<Guid>("DiaconatoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataBatismo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInativacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataMinisterio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataReativacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoUrl10Anos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoUrl15Anos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoUrl20Anos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoUrl25Anos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoUrl5Anos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoUrlConsagracao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Igreja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomePastor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Regiao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TempoAcumuladoEmMeses")
                        .HasColumnType("int");

                    b.HasKey("DiaconatoId");

                    b.ToTable("Diaconato", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
