// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WEB.Data;

#nullable disable

namespace WEB.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260217233243_Membro")]
    partial class Membro
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WEB.Models.Entities.Casal", b =>
                {
                    b.Property<Guid>("CasalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("CargoLocal")
                        .HasMaxLength(80)
                        .HasColumnType("int");

                    b.Property<int>("CargoRegional")
                        .HasMaxLength(80)
                        .HasColumnType("int");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Contato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataBatismo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInativacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataMinisterio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataReativacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IgrejaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("PastorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RegiaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SuperintendenteEstadualId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SuperintendenteRegionalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TempoAcumuladoEmMeses")
                        .HasColumnType("int");

                    b.HasKey("CasalId");

                    b.HasIndex("IgrejaId");

                    b.HasIndex("PastorId");

                    b.HasIndex("RegiaoId");

                    b.HasIndex("SuperintendenteEstadualId");

                    b.HasIndex("SuperintendenteRegionalId");

                    b.ToTable("Casal", (string)null);
                });

            modelBuilder.Entity("WEB.Models.Entities.Crianca", b =>
                {
                    b.Property<Guid>("CriancaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("CargoLocal")
                        .HasMaxLength(80)
                        .HasColumnType("int");

                    b.Property<int>("CargoRegional")
                        .HasMaxLength(80)
                        .HasColumnType("int");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Contato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataBatismo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInativacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataMinisterio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataReativacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IgrejaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("PastorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RegiaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SuperintendenteEstadualId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SuperintendenteRegionalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TempoAcumuladoEmMeses")
                        .HasColumnType("int");

                    b.HasKey("CriancaId");

                    b.HasIndex("IgrejaId");

                    b.HasIndex("PastorId");

                    b.HasIndex("RegiaoId");

                    b.HasIndex("SuperintendenteEstadualId");

                    b.HasIndex("SuperintendenteRegionalId");

                    b.ToTable("Crianca", (string)null);
                });

            modelBuilder.Entity("WEB.Models.Entities.Danca", b =>
                {
                    b.Property<Guid>("DancaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("CargoLocal")
                        .HasMaxLength(80)
                        .HasColumnType("int");

                    b.Property<int>("CargoRegional")
                        .HasMaxLength(80)
                        .HasColumnType("int");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Contato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataBatismo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInativacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataMinisterio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataReativacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IgrejaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("PastorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RegiaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SuperintendenteEstadualId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SuperintendenteRegionalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TempoAcumuladoEmMeses")
                        .HasColumnType("int");

                    b.HasKey("DancaId");

                    b.HasIndex("IgrejaId");

                    b.HasIndex("PastorId");

                    b.HasIndex("RegiaoId");

                    b.HasIndex("SuperintendenteEstadualId");

                    b.HasIndex("SuperintendenteRegionalId");

                    b.ToTable("Danca", (string)null);
                });

            modelBuilder.Entity("WEB.Models.Entities.Diaconato", b =>
                {
                    b.Property<Guid>("DiaconatoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("CargoLocal")
                        .HasMaxLength(80)
                        .HasColumnType("int");

                    b.Property<int?>("CargoRegional")
                        .HasMaxLength(80)
                        .HasColumnType("int");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Contato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataBatismo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInativacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataMinisterio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataReativacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoUrl10Anos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoUrl15Anos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoUrl20Anos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoUrl25Anos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoUrl5Anos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoUrlConsagracao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IgrejaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("PastorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RegiaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SuperintendenteEstadualId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SuperintendenteRegionalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TempoAcumuladoEmMeses")
                        .HasColumnType("int");

                    b.HasKey("DiaconatoId");

                    b.HasIndex("IgrejaId");

                    b.HasIndex("PastorId");

                    b.HasIndex("RegiaoId");

                    b.HasIndex("SuperintendenteEstadualId");

                    b.HasIndex("SuperintendenteRegionalId");

                    b.ToTable("Diaconato", (string)null);
                });

            modelBuilder.Entity("WEB.Models.Entities.Homens", b =>
                {
                    b.Property<Guid>("HomensId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("CargoLocal")
                        .HasMaxLength(80)
                        .HasColumnType("int");

                    b.Property<int>("CargoRegional")
                        .HasMaxLength(80)
                        .HasColumnType("int");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Contato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataBatismo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInativacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataMinisterio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataReativacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IgrejaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("PastorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RegiaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SuperintendenteEstadualId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SuperintendenteRegionalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TempoAcumuladoEmMeses")
                        .HasColumnType("int");

                    b.HasKey("HomensId");

                    b.HasIndex("IgrejaId");

                    b.HasIndex("PastorId");

                    b.HasIndex("RegiaoId");

                    b.HasIndex("SuperintendenteEstadualId");

                    b.HasIndex("SuperintendenteRegionalId");

                    b.ToTable("Homens", (string)null);
                });

            modelBuilder.Entity("WEB.Models.Entities.Igreja", b =>
                {
                    b.Property<Guid>("IgrejaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Endereco")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("RegiaoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IgrejaId");

                    b.HasIndex("RegiaoId");

                    b.ToTable("Igreja", (string)null);
                });

            modelBuilder.Entity("WEB.Models.Entities.JovemAdolescente", b =>
                {
                    b.Property<Guid>("JovemAdolecenteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("CargoLocal")
                        .HasMaxLength(80)
                        .HasColumnType("int");

                    b.Property<int>("CargoRegional")
                        .HasMaxLength(80)
                        .HasColumnType("int");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Contato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataBatismo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInativacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataMinisterio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataReativacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IgrejaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("PastorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RegiaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SuperintendenteEstadualId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SuperintendenteRegionalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TempoAcumuladoEmMeses")
                        .HasColumnType("int");

                    b.HasKey("JovemAdolecenteId");

                    b.HasIndex("IgrejaId");

                    b.HasIndex("PastorId");

                    b.HasIndex("RegiaoId");

                    b.HasIndex("SuperintendenteEstadualId");

                    b.HasIndex("SuperintendenteRegionalId");

                    b.ToTable("JovemAdolescente", (string)null);
                });

            modelBuilder.Entity("WEB.Models.Entities.Louvor", b =>
                {
                    b.Property<Guid>("LouvorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("CargoLocal")
                        .HasMaxLength(80)
                        .HasColumnType("int");

                    b.Property<int>("CargoRegional")
                        .HasMaxLength(80)
                        .HasColumnType("int");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Contato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataBatismo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInativacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataMinisterio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataReativacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IgrejaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("PastorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RegiaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SuperintendenteEstadualId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SuperintendenteRegionalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TempoAcumuladoEmMeses")
                        .HasColumnType("int");

                    b.HasKey("LouvorId");

                    b.HasIndex("IgrejaId");

                    b.HasIndex("PastorId");

                    b.HasIndex("RegiaoId");

                    b.HasIndex("SuperintendenteEstadualId");

                    b.HasIndex("SuperintendenteRegionalId");

                    b.ToTable("Louvor", (string)null);
                });

            modelBuilder.Entity("WEB.Models.Entities.Membro", b =>
                {
                    b.Property<Guid>("MembroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Contato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataBatismo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInativacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataMinisterio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataReativacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IgrejaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("PastorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RegiaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SuperintendenteEstadualId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SuperintendenteRegionalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TempoAcumuladoEmMeses")
                        .HasColumnType("int");

                    b.HasKey("MembroId");

                    b.HasIndex("IgrejaId");

                    b.HasIndex("PastorId");

                    b.HasIndex("RegiaoId");

                    b.HasIndex("SuperintendenteEstadualId");

                    b.HasIndex("SuperintendenteRegionalId");

                    b.ToTable("Membro", (string)null);
                });

            modelBuilder.Entity("WEB.Models.Entities.Midia", b =>
                {
                    b.Property<Guid>("MidiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("CargoLocal")
                        .HasMaxLength(80)
                        .HasColumnType("int");

                    b.Property<int>("CargoRegional")
                        .HasMaxLength(80)
                        .HasColumnType("int");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Contato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataBatismo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInativacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataMinisterio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataReativacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IgrejaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("PastorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RegiaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SuperintendenteEstadualId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SuperintendenteRegionalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TempoAcumuladoEmMeses")
                        .HasColumnType("int");

                    b.HasKey("MidiaId");

                    b.HasIndex("IgrejaId");

                    b.HasIndex("PastorId");

                    b.HasIndex("RegiaoId");

                    b.HasIndex("SuperintendenteEstadualId");

                    b.HasIndex("SuperintendenteRegionalId");

                    b.ToTable("Midia", (string)null);
                });

            modelBuilder.Entity("WEB.Models.Entities.Mulheres", b =>
                {
                    b.Property<Guid>("MulheresId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("CargoLocal")
                        .HasMaxLength(80)
                        .HasColumnType("int");

                    b.Property<int>("CargoRegional")
                        .HasMaxLength(80)
                        .HasColumnType("int");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Contato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataBatismo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInativacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataMinisterio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataReativacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IgrejaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("PastorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RegiaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SuperintendenteEstadualId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SuperintendenteRegionalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TempoAcumuladoEmMeses")
                        .HasColumnType("int");

                    b.HasKey("MulheresId");

                    b.HasIndex("IgrejaId");

                    b.HasIndex("PastorId");

                    b.HasIndex("RegiaoId");

                    b.HasIndex("SuperintendenteEstadualId");

                    b.HasIndex("SuperintendenteRegionalId");

                    b.ToTable("Mulheres", (string)null);
                });

            modelBuilder.Entity("WEB.Models.Entities.Pastores", b =>
                {
                    b.Property<Guid>("PastorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("IgrejaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PastorId");

                    b.HasIndex("IgrejaId");

                    b.ToTable("Pastores", (string)null);
                });

            modelBuilder.Entity("WEB.Models.Entities.Regiao", b =>
                {
                    b.Property<Guid>("RegiaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("SuperintendenteEstadualId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SuperintendenteRegionalId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RegiaoId");

                    b.HasIndex("SuperintendenteEstadualId");

                    b.HasIndex("SuperintendenteRegionalId");

                    b.ToTable("Regiao", (string)null);
                });

            modelBuilder.Entity("WEB.Models.Entities.SuperintendenteEstadual", b =>
                {
                    b.Property<Guid>("SuperintendenteEstadualId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("SuperintendenteEstadualId");

                    b.ToTable("SuperintendenteEstadual", (string)null);
                });

            modelBuilder.Entity("WEB.Models.Entities.SuperintendenteRegional", b =>
                {
                    b.Property<Guid>("SuperintendenteRegionalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("SuperintendenteRegionalId");

                    b.ToTable("SuperintendenteRegional", (string)null);
                });

            modelBuilder.Entity("WEB.Models.Entities.Teatro", b =>
                {
                    b.Property<Guid>("TeatroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("CargoLocal")
                        .HasMaxLength(80)
                        .HasColumnType("int");

                    b.Property<int>("CargoRegional")
                        .HasMaxLength(80)
                        .HasColumnType("int");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Contato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataBatismo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInativacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataMinisterio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataReativacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IgrejaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("PastorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RegiaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SuperintendenteEstadualId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SuperintendenteRegionalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TempoAcumuladoEmMeses")
                        .HasColumnType("int");

                    b.HasKey("TeatroId");

                    b.HasIndex("IgrejaId");

                    b.HasIndex("PastorId");

                    b.HasIndex("RegiaoId");

                    b.HasIndex("SuperintendenteEstadualId");

                    b.HasIndex("SuperintendenteRegionalId");

                    b.ToTable("Teatro", (string)null);
                });

            modelBuilder.Entity("WEB.Models.Entities.Usuario", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("IgrejaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid?>("RegiaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("SenhaHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("datetime2");

                    b.HasKey("UsuarioId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("IgrejaId");

                    b.HasIndex("RegiaoId");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("WEB.Models.Entities.Casal", b =>
                {
                    b.HasOne("WEB.Models.Entities.Igreja", "Igreja")
                        .WithMany("Casals")
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WEB.Models.Entities.Pastores", "Pastor")
                        .WithMany()
                        .HasForeignKey("PastorId");

                    b.HasOne("WEB.Models.Entities.Regiao", "Regiao")
                        .WithMany("Casals")
                        .HasForeignKey("RegiaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WEB.Models.Entities.SuperintendenteEstadual", "SuperintendenteEstadual")
                        .WithMany()
                        .HasForeignKey("SuperintendenteEstadualId");

                    b.HasOne("WEB.Models.Entities.SuperintendenteRegional", "SuperintendenteRegional")
                        .WithMany()
                        .HasForeignKey("SuperintendenteRegionalId");

                    b.Navigation("Igreja");

                    b.Navigation("Pastor");

                    b.Navigation("Regiao");

                    b.Navigation("SuperintendenteEstadual");

                    b.Navigation("SuperintendenteRegional");
                });

            modelBuilder.Entity("WEB.Models.Entities.Crianca", b =>
                {
                    b.HasOne("WEB.Models.Entities.Igreja", "Igreja")
                        .WithMany("Criancas")
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WEB.Models.Entities.Pastores", "Pastor")
                        .WithMany()
                        .HasForeignKey("PastorId");

                    b.HasOne("WEB.Models.Entities.Regiao", "Regiao")
                        .WithMany("Criancas")
                        .HasForeignKey("RegiaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WEB.Models.Entities.SuperintendenteEstadual", "SuperintendenteEstadual")
                        .WithMany()
                        .HasForeignKey("SuperintendenteEstadualId");

                    b.HasOne("WEB.Models.Entities.SuperintendenteRegional", "SuperintendenteRegional")
                        .WithMany()
                        .HasForeignKey("SuperintendenteRegionalId");

                    b.Navigation("Igreja");

                    b.Navigation("Pastor");

                    b.Navigation("Regiao");

                    b.Navigation("SuperintendenteEstadual");

                    b.Navigation("SuperintendenteRegional");
                });

            modelBuilder.Entity("WEB.Models.Entities.Danca", b =>
                {
                    b.HasOne("WEB.Models.Entities.Igreja", "Igreja")
                        .WithMany("Dancas")
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WEB.Models.Entities.Pastores", "Pastor")
                        .WithMany()
                        .HasForeignKey("PastorId");

                    b.HasOne("WEB.Models.Entities.Regiao", "Regiao")
                        .WithMany("Dancas")
                        .HasForeignKey("RegiaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WEB.Models.Entities.SuperintendenteEstadual", "SuperintendenteEstadual")
                        .WithMany()
                        .HasForeignKey("SuperintendenteEstadualId");

                    b.HasOne("WEB.Models.Entities.SuperintendenteRegional", "SuperintendenteRegional")
                        .WithMany()
                        .HasForeignKey("SuperintendenteRegionalId");

                    b.Navigation("Igreja");

                    b.Navigation("Pastor");

                    b.Navigation("Regiao");

                    b.Navigation("SuperintendenteEstadual");

                    b.Navigation("SuperintendenteRegional");
                });

            modelBuilder.Entity("WEB.Models.Entities.Diaconato", b =>
                {
                    b.HasOne("WEB.Models.Entities.Igreja", "Igreja")
                        .WithMany("Diaconos")
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WEB.Models.Entities.Pastores", "Pastor")
                        .WithMany()
                        .HasForeignKey("PastorId");

                    b.HasOne("WEB.Models.Entities.Regiao", "Regiao")
                        .WithMany("Diaconos")
                        .HasForeignKey("RegiaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WEB.Models.Entities.SuperintendenteEstadual", "SuperintendenteEstadual")
                        .WithMany("Diaconos")
                        .HasForeignKey("SuperintendenteEstadualId");

                    b.HasOne("WEB.Models.Entities.SuperintendenteRegional", "SuperintendenteRegional")
                        .WithMany("Diaconos")
                        .HasForeignKey("SuperintendenteRegionalId");

                    b.Navigation("Igreja");

                    b.Navigation("Pastor");

                    b.Navigation("Regiao");

                    b.Navigation("SuperintendenteEstadual");

                    b.Navigation("SuperintendenteRegional");
                });

            modelBuilder.Entity("WEB.Models.Entities.Homens", b =>
                {
                    b.HasOne("WEB.Models.Entities.Igreja", "Igreja")
                        .WithMany("Homens")
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WEB.Models.Entities.Pastores", "Pastor")
                        .WithMany()
                        .HasForeignKey("PastorId");

                    b.HasOne("WEB.Models.Entities.Regiao", "Regiao")
                        .WithMany("Homens")
                        .HasForeignKey("RegiaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WEB.Models.Entities.SuperintendenteEstadual", "SuperintendenteEstadual")
                        .WithMany()
                        .HasForeignKey("SuperintendenteEstadualId");

                    b.HasOne("WEB.Models.Entities.SuperintendenteRegional", "SuperintendenteRegional")
                        .WithMany()
                        .HasForeignKey("SuperintendenteRegionalId");

                    b.Navigation("Igreja");

                    b.Navigation("Pastor");

                    b.Navigation("Regiao");

                    b.Navigation("SuperintendenteEstadual");

                    b.Navigation("SuperintendenteRegional");
                });

            modelBuilder.Entity("WEB.Models.Entities.Igreja", b =>
                {
                    b.HasOne("WEB.Models.Entities.Regiao", "Regiao")
                        .WithMany("Igrejas")
                        .HasForeignKey("RegiaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Regiao");
                });

            modelBuilder.Entity("WEB.Models.Entities.JovemAdolescente", b =>
                {
                    b.HasOne("WEB.Models.Entities.Igreja", "Igreja")
                        .WithMany("JovemAdolecentes")
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WEB.Models.Entities.Pastores", "Pastor")
                        .WithMany()
                        .HasForeignKey("PastorId");

                    b.HasOne("WEB.Models.Entities.Regiao", "Regiao")
                        .WithMany("JovemAdolecentes")
                        .HasForeignKey("RegiaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WEB.Models.Entities.SuperintendenteEstadual", "SuperintendenteEstadual")
                        .WithMany()
                        .HasForeignKey("SuperintendenteEstadualId");

                    b.HasOne("WEB.Models.Entities.SuperintendenteRegional", "SuperintendenteRegional")
                        .WithMany()
                        .HasForeignKey("SuperintendenteRegionalId");

                    b.Navigation("Igreja");

                    b.Navigation("Pastor");

                    b.Navigation("Regiao");

                    b.Navigation("SuperintendenteEstadual");

                    b.Navigation("SuperintendenteRegional");
                });

            modelBuilder.Entity("WEB.Models.Entities.Louvor", b =>
                {
                    b.HasOne("WEB.Models.Entities.Igreja", "Igreja")
                        .WithMany("Louvors")
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WEB.Models.Entities.Pastores", "Pastor")
                        .WithMany()
                        .HasForeignKey("PastorId");

                    b.HasOne("WEB.Models.Entities.Regiao", "Regiao")
                        .WithMany("Louvors")
                        .HasForeignKey("RegiaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WEB.Models.Entities.SuperintendenteEstadual", "SuperintendenteEstadual")
                        .WithMany()
                        .HasForeignKey("SuperintendenteEstadualId");

                    b.HasOne("WEB.Models.Entities.SuperintendenteRegional", "SuperintendenteRegional")
                        .WithMany()
                        .HasForeignKey("SuperintendenteRegionalId");

                    b.Navigation("Igreja");

                    b.Navigation("Pastor");

                    b.Navigation("Regiao");

                    b.Navigation("SuperintendenteEstadual");

                    b.Navigation("SuperintendenteRegional");
                });

            modelBuilder.Entity("WEB.Models.Entities.Membro", b =>
                {
                    b.HasOne("WEB.Models.Entities.Igreja", "Igreja")
                        .WithMany("Membros")
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WEB.Models.Entities.Pastores", "Pastor")
                        .WithMany()
                        .HasForeignKey("PastorId");

                    b.HasOne("WEB.Models.Entities.Regiao", "Regiao")
                        .WithMany("Membros")
                        .HasForeignKey("RegiaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WEB.Models.Entities.SuperintendenteEstadual", "SuperintendenteEstadual")
                        .WithMany()
                        .HasForeignKey("SuperintendenteEstadualId");

                    b.HasOne("WEB.Models.Entities.SuperintendenteRegional", "SuperintendenteRegional")
                        .WithMany()
                        .HasForeignKey("SuperintendenteRegionalId");

                    b.Navigation("Igreja");

                    b.Navigation("Pastor");

                    b.Navigation("Regiao");

                    b.Navigation("SuperintendenteEstadual");

                    b.Navigation("SuperintendenteRegional");
                });

            modelBuilder.Entity("WEB.Models.Entities.Midia", b =>
                {
                    b.HasOne("WEB.Models.Entities.Igreja", "Igreja")
                        .WithMany("Midias")
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WEB.Models.Entities.Pastores", "Pastor")
                        .WithMany()
                        .HasForeignKey("PastorId");

                    b.HasOne("WEB.Models.Entities.Regiao", "Regiao")
                        .WithMany("Midias")
                        .HasForeignKey("RegiaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WEB.Models.Entities.SuperintendenteEstadual", "SuperintendenteEstadual")
                        .WithMany()
                        .HasForeignKey("SuperintendenteEstadualId");

                    b.HasOne("WEB.Models.Entities.SuperintendenteRegional", "SuperintendenteRegional")
                        .WithMany()
                        .HasForeignKey("SuperintendenteRegionalId");

                    b.Navigation("Igreja");

                    b.Navigation("Pastor");

                    b.Navigation("Regiao");

                    b.Navigation("SuperintendenteEstadual");

                    b.Navigation("SuperintendenteRegional");
                });

            modelBuilder.Entity("WEB.Models.Entities.Mulheres", b =>
                {
                    b.HasOne("WEB.Models.Entities.Igreja", "Igreja")
                        .WithMany("Mulheres")
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WEB.Models.Entities.Pastores", "Pastor")
                        .WithMany()
                        .HasForeignKey("PastorId");

                    b.HasOne("WEB.Models.Entities.Regiao", "Regiao")
                        .WithMany("Mulheres")
                        .HasForeignKey("RegiaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WEB.Models.Entities.SuperintendenteEstadual", "SuperintendenteEstadual")
                        .WithMany()
                        .HasForeignKey("SuperintendenteEstadualId");

                    b.HasOne("WEB.Models.Entities.SuperintendenteRegional", "SuperintendenteRegional")
                        .WithMany()
                        .HasForeignKey("SuperintendenteRegionalId");

                    b.Navigation("Igreja");

                    b.Navigation("Pastor");

                    b.Navigation("Regiao");

                    b.Navigation("SuperintendenteEstadual");

                    b.Navigation("SuperintendenteRegional");
                });

            modelBuilder.Entity("WEB.Models.Entities.Pastores", b =>
                {
                    b.HasOne("WEB.Models.Entities.Igreja", "Igreja")
                        .WithMany("Pastores")
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Igreja");
                });

            modelBuilder.Entity("WEB.Models.Entities.Regiao", b =>
                {
                    b.HasOne("WEB.Models.Entities.SuperintendenteEstadual", "SuperintendenteEstadual")
                        .WithMany("Regioes")
                        .HasForeignKey("SuperintendenteEstadualId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WEB.Models.Entities.SuperintendenteRegional", "SuperintendenteRegional")
                        .WithMany("Regioes")
                        .HasForeignKey("SuperintendenteRegionalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SuperintendenteEstadual");

                    b.Navigation("SuperintendenteRegional");
                });

            modelBuilder.Entity("WEB.Models.Entities.Teatro", b =>
                {
                    b.HasOne("WEB.Models.Entities.Igreja", "Igreja")
                        .WithMany("Teatros")
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WEB.Models.Entities.Pastores", "Pastor")
                        .WithMany()
                        .HasForeignKey("PastorId");

                    b.HasOne("WEB.Models.Entities.Regiao", "Regiao")
                        .WithMany("Teatros")
                        .HasForeignKey("RegiaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WEB.Models.Entities.SuperintendenteEstadual", "SuperintendenteEstadual")
                        .WithMany()
                        .HasForeignKey("SuperintendenteEstadualId");

                    b.HasOne("WEB.Models.Entities.SuperintendenteRegional", "SuperintendenteRegional")
                        .WithMany()
                        .HasForeignKey("SuperintendenteRegionalId");

                    b.Navigation("Igreja");

                    b.Navigation("Pastor");

                    b.Navigation("Regiao");

                    b.Navigation("SuperintendenteEstadual");

                    b.Navigation("SuperintendenteRegional");
                });

            modelBuilder.Entity("WEB.Models.Entities.Usuario", b =>
                {
                    b.HasOne("WEB.Models.Entities.Igreja", "Igreja")
                        .WithMany("Usuarios")
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WEB.Models.Entities.Regiao", "Regiao")
                        .WithMany("Usuarios")
                        .HasForeignKey("RegiaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Igreja");

                    b.Navigation("Regiao");
                });

            modelBuilder.Entity("WEB.Models.Entities.Igreja", b =>
                {
                    b.Navigation("Casals");

                    b.Navigation("Criancas");

                    b.Navigation("Dancas");

                    b.Navigation("Diaconos");

                    b.Navigation("Homens");

                    b.Navigation("JovemAdolecentes");

                    b.Navigation("Louvors");

                    b.Navigation("Membros");

                    b.Navigation("Midias");

                    b.Navigation("Mulheres");

                    b.Navigation("Pastores");

                    b.Navigation("Teatros");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("WEB.Models.Entities.Regiao", b =>
                {
                    b.Navigation("Casals");

                    b.Navigation("Criancas");

                    b.Navigation("Dancas");

                    b.Navigation("Diaconos");

                    b.Navigation("Homens");

                    b.Navigation("Igrejas");

                    b.Navigation("JovemAdolecentes");

                    b.Navigation("Louvors");

                    b.Navigation("Membros");

                    b.Navigation("Midias");

                    b.Navigation("Mulheres");

                    b.Navigation("Teatros");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("WEB.Models.Entities.SuperintendenteEstadual", b =>
                {
                    b.Navigation("Diaconos");

                    b.Navigation("Regioes");
                });

            modelBuilder.Entity("WEB.Models.Entities.SuperintendenteRegional", b =>
                {
                    b.Navigation("Diaconos");

                    b.Navigation("Regioes");
                });
#pragma warning restore 612, 618
        }
    }
}
